dashboard.base-url=http://146.56.152.131

spring.datasource.url=jdbc:mariadb://mariadb:3306/psmsdb
spring.datasource.username=psmsapp
spring.datasource.password=${DB_APP_PASSWD}

spring.flyway.url=jdbc:mariadb://mariadb:3306/psmsdb
spring.flyway.user=psmsadm
spring.flyway.password=${DB_ADM_PASSWD}
