stock.collection.enabled=true

renderer.enabled=true
renderer.url=http://market-monitor-renderer:3000

dashboard.base-url=https://eolmae.duckdns.org

krx.login-id=${KRX_ID}
krx.login-pw=${KRX_PW}

spring.datasource.url=jdbc:postgresql://market-monitor-postgres:5432/market_monitor_db
spring.datasource.password=${DB_PASSWORD}
