services:
  psmsapp:
    image: ghcr.io/fwangchanju/psms:latest
    container_name: psmsapp
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_APP_PASSWD=${DB_APP_PASSWD}
      - DB_ADM_PASSWD=${DB_ADM_PASSWD}
      - KIWOOM_APP_KEY=${KIWOOM_APP_KEY}
      - KIWOOM_SECRET=${KIWOOM_SECRET}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend:
    external: true
